### ISSUE TITLE
unsupported operand type(s) for +=: 'NoneType' and 'NoneType' error in langfuse

### ISSUE THREAD

**Issue by forcewake** [michaelpoluektov/OWUI-ReAct#2]
Hi @michaelpoluektov,

Do you have any idea what is wrong? All valves was setup properly but I've got an error:

![image](https://github.com/user-attachments/assets/6a51c781-4bf5-47fe-8835-43e352e7b869)

And `unsupported operand type(s) for +=: 'NoneType' and 'NoneType' error` in langfuse

![image](https://github.com/user-attachments/assets/59a01a85-df69-4ba6-9c00-b23caeef6ff0)

Thank you!

**Comment by michaelpoluektov** [comment]
Do you have any other logs? `docker logs open-webui` if you're using docker

**Comment by michaelpoluektov** [comment]
Can't reproduce without more info.
